spring.application.name=earthquake-detector

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/earthquake_detector_dev_db
spring.datasource.username=username
spring.datasource.password=password

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Enable Flyway
spring.flyway.enabled=true

app.feed.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
app.feed.interval=60000

spring.http.client.connect-timeout=5000
spring.http.client.read-timeout=10000